version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sample-python-telegram-bot-aws-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10nlw41n89q5g"
s3_prefix = "sample-python-telegram-bot-aws-serverless"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
confirm_changeset = true
